version: '3.1'
services:
  stats-server:
    build: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb?user=test&password=test&createDatabaseIfNotExist=true

  stats-db:
    image: postgres:14-alpine
    ports:
        - "6542:5432"
    environment:
        - POSTGRES_DB=statsdb
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test

  ewm-service:
    build: server
    image: explorewithme-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - EXPLORE_WITH_ME_STATS_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/serverdb?user=test&password=test&createDatabaseIfNotExist=true


  ewm-db:
    image: postgres:14-alpine
    ports:
        - "6541:5432"
    environment:
      - POSTGRES_DB=serverdb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
