CREATE TABLE IF NOT EXISTS endpoint_hit
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app  VARCHAR(255)                             NOT NULL,
    uri  VARCHAR(250)                             NOT NULL,
    ip   VARCHAR(250)                             NOT NULL,
    timestamp TIMESTAMP                           NOT NULL,
    CONSTRAINT pk_endpoint_hit PRIMARY KEY (id)
);